const $=s=>document.querySelector(s);const job=$('#jobText'),resume=$('#resumeText');
const stop=new Set('a o e de da do das dos em para por com sem um uma uns umas que se na no nas nos ao aos as os é ser ter como sua seu suas seus vaga buscamos candidato candidata profissional experiência experiencias experiência conhecimento conhecimentos habilidade habilidades requisito requisitos responsabilidades diferencial diferenciais desejável desejaveis desejavel ensino superior completo trabalho atuar atuação'.split(/\s+/));
const techTerms=['javascript','typescript','react','node','node.js','python','java','c#','c++','php','sql','mysql','postgresql','mongodb','aws','azure','gcp','docker','kubernetes','linux','windows','git','github','active directory','tcp/ip','redes','firewall','vpn','help desk','service desk','itil','scrum','kanban','excel','power bi','sap','salesforce','figma','html','css','rest','api','apis','devops','ci/cd','terraform','ansible','vmware','proxmox','office 365','microsoft 365','inglês','ingles'];
function norm(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9+#./-]+/g,' ').replace(/\s+/g,' ').trim()}
function keywords(text){const n=norm(text);const out=new Set();techTerms.forEach(t=>{if(n.includes(norm(t)))out.add(t)});const words=n.split(' ').filter(w=>w.length>=4&&!stop.has(w)&&!/^[0-9]+$/.test(w));const freq={};words.forEach(w=>freq[w]=(freq[w]||0)+1);Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,18).forEach(([w])=>out.add(w));return [...out].slice(0,24)}
function optimize(text,found){let clean=text.replace(/\t/g,' ').replace(/ {2,}/g,' ').replace(/\n{3,}/g,'\n\n').trim();const lines=clean.split('\n').map(x=>x.trim()).filter(Boolean);const contact=lines.slice(0,4);const body=lines.slice(4);const safe=found.slice(0,8);let summary='';if(safe.length){summary=`\n\nRESUMO DE COMPETÊNCIAS\n${safe.map(k=>'• '+k).join('\n')}`}return `${contact.join('\n')}${summary}\n\nEXPERIÊNCIA E FORMAÇÃO\n${body.join('\n')}`.replace(/\n{3,}/g,'\n\n').trim()}
function updateCount(el,target){target.textContent=`${el.value.length} caracteres`}
job.addEventListener('input',()=>updateCount(job,$('#jobCount')));resume.addEventListener('input',()=>updateCount(resume,$('#resumeCount')));
$('#sampleJob').onclick=()=>{job.value='Analista de Suporte de TI. Responsável por atendimento ao usuário, suporte a Windows e Linux, configuração de redes TCP/IP, Active Directory, Microsoft 365, VPN e documentação de chamados. Conhecimento em AWS, ITIL, Git e segurança da informação será diferencial.';updateCount(job,$('#jobCount'))};
$('#sampleResume').onclick=()=>{resume.value='ANTONIO JONAS\nRio de Janeiro - RJ | contato@email.com\n\nOBJETIVO\nAtuar na área de suporte e infraestrutura de TI.\n\nEXPERIÊNCIA\nMais de 20 anos com manutenção de computadores e notebooks, atendimento técnico, diagnóstico de hardware e software, suporte a Windows e Linux, redes TCP/IP, VPN e virtualização com Proxmox.\n\nCONHECIMENTOS\nWindows, Linux, redes, TCP/IP, VPN, Proxmox, Git, suporte ao usuário, manutenção de hardware.\n\nFORMAÇÃO E CURSOS\nEnsino médio completo. Cursos de Linux, redes, segurança e computação em nuvem.';updateCount(resume,$('#resumeCount'))};
$('#analyzeBtn').onclick=()=>{if(job.value.trim().length<40||resume.value.trim().length<40){alert('Cole uma descrição de vaga e um currículo com conteúdo suficiente para análise.');return}const ks=keywords(job.value);const r=norm(resume.value);const found=ks.filter(k=>r.includes(norm(k)));const missing=ks.filter(k=>!r.includes(norm(k)));const score=ks.length?Math.round(found.length/ks.length*100):0;$('#results').classList.remove('hidden');$('#scoreValue').textContent=score+'%';$('#scoreBar').style.width=score+'%';$('#foundCount').textContent=found.length;$('#missingCount').textContent=missing.length;$('#totalCount').textContent=ks.length;$('#scoreLabel').textContent=score>=80?'Excelente aderência':score>=60?'Boa aderência':score>=40?'Aderência parcial':'Baixa aderência';$('#scoreMessage').textContent=score>=70?'Seu currículo conversa bem com a vaga. Revise apenas as lacunas que realmente correspondem ao seu repertório.':'Há espaço para melhorar a clareza e a aderência, mas sem adicionar experiências que você não possui.';$('#foundKeywords').innerHTML=found.length?found.map(k=>`<span class="chip ok">${k}</span>`).join(''):'<span class="hint">Nenhuma palavra-chave relevante encontrada.</span>';$('#missingKeywords').innerHTML=missing.length?missing.map(k=>`<span class="chip miss">${k}</span>`).join(''):'<span class="hint">Nenhuma lacuna relevante detectada.</span>';$('#optimizedResume').textContent=optimize(resume.value,found);$('#results').scrollIntoView({behavior:'smooth',block:'start'})};
$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('#optimizedResume').textContent);$('#copyBtn').textContent='Copiado!';setTimeout(()=>$('#copyBtn').textContent='Copiar texto',1400)};$('#printBtn').onclick=()=>window.print();
